version: '3'
services:
   chile3d-mongodb:
      image: 'mongo:3.6.8'
      container_name: chile3d-mongodb
      ports:
         - '27017:27017'
      expose:
         - '27017'
      environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: example
      command: mongod --bind_ip_all
   chile3d-api:
      container_name: chile3d-api
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '8000:8000' # Adjust the port mapping as needed
      depends_on:
         - chile3d-mongodb # Ensures that mongodb-chile3d is started before your_service_name
networks:
   default:

